/**
 * Miro Integration Configuration Guide
 *
 * To enable Miro BoardsPicker integration in your video calls, follow these steps:
 *
 * 1. Create a Miro App:
 *    - Go to https://miro.com/app/settings/account/apps
 *    - Click "Create new app"
 *    - Select "OAuth 2.0" as the app type
 *    - Set your redirect URI (e.g., http://localhost:3000 for development)
 *
 * 2. Get Your Credentials:
 *    - Client ID: Available in your app settings
 *    - Client Secret: Available in your app settings
 *
 * 3. Add to Environment Variables:
 *
 *    .env.local:
 *    ```
 *    NEXT_PUBLIC_MIRO_CLIENT_ID=your_client_id_here
 *    MIRO_CLIENT_SECRET=your_client_secret_here
 *    ```
 *
 * 4. Optional: Miro API Configuration
 *    If you plan to use additional Miro API features:
 *    ```
 *    MIRO_API_KEY=your_api_key_here
 *    MIRO_API_URL=https://api.miro.com/v2
 *    ```
 *
 * 5. Scopes Required (set in your Miro App settings):
 *    - boards:read
 *    - boards:write
 *    - identity:read
 *
 * Security Notes:
 * - Never commit your MIRO_CLIENT_SECRET to version control
 * - Always use HTTPS in production
 * - The JWT token generated by /api/miro-token has a 1-hour expiration
 * - Tokens are marked with no-cache headers to prevent caching
 */

export const MIRO_CONFIG = {
  // These values are loaded from environment variables
  clientId: process.env.NEXT_PUBLIC_MIRO_CLIENT_ID,
  clientSecret: process.env.MIRO_CLIENT_SECRET,
  apiUrl: process.env.MIRO_API_URL || "https://api.miro.com/v2",
  apiKey: process.env.MIRO_API_KEY,

  // Token configuration
  tokenExpiration: 3600, // 1 hour in seconds

  // BoardsPicker configuration
  boardsPicker: {
    allowCreateAnonymousBoards: true,
    action: "access-link",
  },
};

/**
 * Example usage in your component:
 *
 * const tokenResponse = await fetch("/api/miro-token", {
 *   method: "POST",
 *   headers: { "Content-Type": "application/json" },
 * });
 *
 * const { token } = await tokenResponse.json();
 *
 * window.miroBoardsPicker.open({
 *   clientId: process.env.NEXT_PUBLIC_MIRO_CLIENT_ID,
 *   action: "access-link",
 *   allowCreateAnonymousBoards: true,
 *   getToken: () => Promise.resolve(token),
 *   success: (data) => {
 *     console.log("Board selected:", data);
 *     setMiroEmbedHtml(data.embedHtml);
 *   },
 *   error: (error) => {
 *     console.error("Miro error:", error);
 *   },
 *   cancel: () => {
 *     console.log("Miro picker cancelled");
 *   },
 * });
 */
